name: Lets go

on:
  push:
  pull_request:
    types: [ opened, reopened, synchronize ]
  workflow_dispatch:
  schedule:
    - cron: '0 */8 * * *'

jobs:

  run:
    name: Run
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          java-version: '19'
          distribution: 'temurin'
          cache: 'maven'

      - name: Run Selenium Grid
        uses: isbang/compose-action@v1.4.1
        with:
          compose-file: "./docker/docker-compose-v3.yml"

      - name: Build with Maven
        id: RunTests
        run: mvn clean test -Dsurefire.suiteXmlFiles=./src/test/resources/tests.xml -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn -B -V