name: Hosted Test Orchestration

on:
  push:
  pull_request:
    types: [ opened, reopened, synchronize ]
  workflow_dispatch:
  schedule:
    - cron: '0 */1 * * *'

env:
  DISPLAY: :99
  SAUCE_USERNAME: ${{ vars.SAUCE_USERNAME }}
  SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}
  DOCKER_USERNAME: ${{ vars.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:

  docker_hub:
    name: Setup Container
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.meta.outputs.tags }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ vars.DOCKER_USERNAME }}/photon-demo-java
          tags: type=sha
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}

  orchestrated_eu:
    name: Run Tests Hosted by Sauce Labs EU
    needs: docker_hub
    runs-on: ubuntu-latest
    container: saucelabs/saucectl:latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Run Saucectl
        env:
          DOCKER_IMAGE: ${{ needs.docker_hub.outputs.tag }}
          BUILD_TAG: EU-Hosted-1.${{ github.run_number }}
          REGION: eu-central-1
        run: saucectl run -c .sauce/config_eu.yml

  orchestrated_us:
    name: Run Tests Hosted by Sauce Labs US
    needs: docker_hub
    runs-on: ubuntu-latest
    container: saucelabs/saucectl:latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Run Saucectl
        env:
          DOCKER_IMAGE: ${{ needs.docker_hub.outputs.tag }}
          BUILD_TAG: US-Hosted-1.${{ github.run_number }}
          REGION: us-west-1
        run: saucectl run

  sauce_grid:
    name: Run Tests on Sauce Labs Grid
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          java-version: '19'
          distribution: 'temurin'
      - name: Build with Maven
        run: mvn clean test -Dsurefire.suiteXmlFiles=./src/test/resources/saucelabs.xml -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn -B -V
        env:
          SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
          SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}
          BUILD_TAG: DevOps-Live-SL-Grid-1.${{ github.run_number }}