name: Hosted Test Orchestration

on:
  push:
  pull_request:
    types: [ opened, reopened, synchronize ]
  workflow_dispatch:
  schedule:
    - cron: '0 */8 * * *'

env:
  DISPLAY: :99
  SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
  SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:

  docker_hub:
    name: Setup Container
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.generate-uuid.outputs.uuid }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Set UUID
        id: generate-uuid
        uses: filipstefansson/uuid-action@v1
        with:
          name: ${{ github.sha }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          #context: ./
          push: true
          tags: ${{ steps.generate-uuid.outputs.uuid }}

  orchestrated:
    name: Run Tests Hosted by Sauce Labs
    needs: docker_hub
    runs-on: ubuntu-latest
    container: saucelabs/saucectl:latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Run Saucectl
        env:
          DOCKER_IMAGE: ${{ needs.docker_hub.outputs.tag }}
        working-directory: java
        run: saucectl run