apiVersion: v1alpha
kind: imagerunner
sauce:
region: us-west-1
suites:
  - name: Hosted Test Orchestration Demo
    image: $DOCKER_IMAGE
    entrypoint: "mvn clean test -Dsurefire.suiteXmlFiles=./src/test/resources/saucelabs.xml"
    imagePullAuth:
      user: $DOCKER_USERNAME
      token: $DOCKER_PASSWORD