apiVersion: v1alpha
kind: imagerunner
sauce:
region: us-west-1
suites:
  - name: Hosted Test Orchestration Demo
    #image: $DOCKER_IMAGE
    image: sceiler/photon-demo-java:sha-11e9086
    entrypoint: "mvn clean test -Dsurefire.suiteXmlFiles=./src/test/resources/remote.xml"
    imagePullAuth:
      user: $DOCKER_USERNAME
      token: $DOCKER_PASSWORD